apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  labels:
    app: springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot-deployment
        image: 13491a03c5/springboot-maven-course-micro-svc:#(Build.BuildId)#
        ports:
        - containerPort: 8080
